const linkedInPost = (activityId) => `https://www.linkedin.com/feed/update/urn:li:activity:${activityId}`

const media = (row, index, width, height, alt, caption, type = "photo") => ({
  src: `/media/row-${String(row).padStart(4, "0")}/media-${String(index).padStart(3, "0")}.jpg`,
  width,
  height,
  orientation: height > width * 1.18 ? "portrait" : width > height * 1.35 ? "landscape" : "square",
  type,
  alt,
  caption,
})

const certificate = (filename, width, height, alt, caption) => ({
  src: `/media/certificates/${filename}`,
  width,
  height,
  orientation: height > width ? "portrait" : "landscape",
  type: "certificate",
  alt,
  caption,
})

export const journeyEntries = [
  {
    id: "cyberwave-builder",
    dateLabel: "2026",
    sortDate: "2026-06-01",
    era: "btech",
    themes: ["build", "learn"],
    title: "Into Robotics and Physical AI",
    summary: "Selected as a Community Builder for the Cyberwave Builders Program.",
    details: "Beginning hands-on work with remotely controlled robotic arms, multimodal agents, and physical automation workflows.",
    postUrl: linkedInPost("7465501179356262400"),
    media: [media(1, 1, 800, 770, "Orange Cyberwave robotic arm with the words Time to build physical AI.", "Cyberwave Builders Program announcement")],
  },
  {
    id: "gemma-workshop",
    dateLabel: "2026",
    sortDate: "2026-05-16",
    era: "btech",
    themes: ["learn", "build"],
    title: "Edge AI at Google",
    summary: "Joined a hands-on Gemma workshop focused on local and scalable model deployment.",
    details: "Explored model architecture, LiteRT, vLLM, Cloud Run, and deployment workflows across edge devices and cloud GPUs.",
    postUrl: linkedInPost("7461745384135241728"),
    media: [
      media(3, 2, 800, 742, "Nishith giving two thumbs up in front of a Google Cloud workshop wall.", "Build with AI: Gemma workshop"),
      media(3, 3, 800, 451, "Presenter speaking beside a Gemma workshop slide.", "Gemma architecture and edge deployment session"),
      media(3, 4, 800, 451, "Laptop displaying Gemma model and deployment information.", "Hands-on Gemma deployment work"),
    ],
  },
  {
    id: "openenv-finalist",
    dateLabel: "April 2026",
    sortDate: "2026-04-26",
    era: "btech",
    themes: ["compete", "build"],
    title: "OpenEnv Grand Finale",
    summary: "Qualified for the Meta PyTorch OpenEnv Hackathon grand finale at Scaler School of Technology.",
    details: "Built an experimental reinforcement-learning environment for training small language models toward more humane marketing pitches.",
    postUrl: linkedInPost("7461738181097447424"),
    fieldNotes: [
      { label: "Grand finale recap", url: linkedInPost("7461738181097447424") },
      { label: "Live from the hackathon floor", url: linkedInPost("7453748628139008000") },
      { label: "Qualification announcement", url: linkedInPost("7449185679739183104") },
    ],
    media: [
      media(4, 1, 800, 565, "Certificate confirming qualification in Round 1 of the Meta PyTorch OpenEnv Hackathon.", "OpenEnv Hackathon qualification certificate", "certificate"),
      media(4, 2, 800, 859, "OpenEnv Hackathon participant badge and event shirt.", "At the OpenEnv grand finale"),
      media(5, 1, 800, 1418, "Nishith posing in front of the Meta PyTorch OpenEnv Hackathon grand-finale backdrop.", "On the OpenEnv grand-finale floor"),
      media(5, 2, 800, 1418, "Nishith presenting beside the signed OpenEnv Hackathon banner in Bengaluru.", "Presenting at the 36-hour OpenEnv sprint"),
    ],
  },
  {
    id: "industry-learning-2026",
    dateLabel: "February–April 2026",
    sortDate: "2026-04-23",
    era: "btech",
    themes: ["learn", "build"],
    title: "Learning with the Builder Community",
    summary: "Attended AWS Summit, GitHub Constellation, Gemini 3, and Build India events in Bengaluru.",
    details: "A concentrated season of cloud, developer tooling, frontier-model, agent, and hackathon learning alongside industry communities.",
    postUrl: linkedInPost("7453357798765174785"),
    fieldNotes: [
      { label: "AWS Summit", url: linkedInPost("7453357798765174785") },
      { label: "GitHub Constellation", url: linkedInPost("7448781154217930752") },
      { label: "Gemini 3 Hackathon", url: linkedInPost("7430135339156996096") },
      { label: "Build India", url: linkedInPost("7430170069449510913") },
    ],
    media: [
      media(6, 2, 800, 468, "Nishith standing beside an AWS Summit Bengaluru sign.", "AWS Summit Bengaluru 2026"),
      media(8, 2, 800, 582, "Nishith at GitHub Constellation 2026 India.", "GitHub Constellation 2026 India"),
      media(12, 2, 800, 451, "Gemini 3 Bengaluru Hackathon venue and presentation screen.", "Gemini 3 Bengaluru Hackathon"),
      media(11, 3, 800, 451, "Nishith at the Build India hackathon.", "Build India: Anthropic × Replit × Lightspeed India"),
    ],
  },
  {
    id: "netdata-devops-show",
    dateLabel: "February 13, 2026",
    sortDate: "2026-02-13",
    era: "btech",
    themes: ["lead", "learn"],
    title: "From Home Server to Netdata Advocate",
    summary: "Volunteered with Netdata at India DevOps Show after first using the project for home-server monitoring.",
    details: "Moved from open-source user to booth volunteer, discussing observability and performance monitoring with engineering leaders, founders, and DevOps practitioners.",
    postUrl: linkedInPost("7429233593169756160"),
    media: [
      media(13, 1, 720, 1280, "Volunteers standing in front of the Netdata booth at India DevOps Show 2026.", "Volunteering with Netdata at India DevOps Show"),
      media(13, 2, 800, 1418, "Netdata lanyard, USB drive, stickers, and SRE-themed items from India DevOps Show.", "Netdata volunteer and observability kit"),
      media(13, 3, 800, 451, "Nishith wearing an observability-themed shirt at India DevOps Show.", "From Netdata user to community advocate"),
    ],
  },
  {
    id: "deepwatch-internship",
    dateLabel: "February 2026",
    sortDate: "2026-02-01",
    era: "btech",
    themes: ["build", "learn"],
    title: "Software Engineering at Deepwatch",
    summary: "Started as a Software Engineer Intern at cybersecurity company Deepwatch.",
    details: "Transitioned from campus projects and independent security research into production software engineering in a hybrid product team.",
    postUrl: linkedInPost("7434177685377040384"),
    media: [
      media(10, 1, 800, 565, "Deepwatch onboarding items arranged on a table.", "Beginning the Deepwatch internship"),
      media(10, 2, 800, 451, "Deepwatch office interior with workstations.", "Deepwatch Bengaluru office"),
    ],
  },
  {
    id: "dastaan-2025",
    dateLabel: "October 2025",
    sortDate: "2025-10-12",
    era: "btech",
    themes: ["lead", "compete", "build"],
    title: "Leading and Competing at Dastaan '25",
    summary: "Served as Website Team Lead and secured second place in Hack Your Life.",
    details: "Combined core organizing responsibility with a competition result during Amrita Bengaluru's national-level multifest.",
    postUrl: linkedInPost("7404945538313256960"),
    media: [
      media(15, 1, 800, 558, "Certificate of excellence for second place in Hack Your Life at Dastaan 2025.", "Hack Your Life second-place certificate", "certificate"),
      media(15, 2, 1275, 975, "Certificate recognizing Nishith's leadership and contribution as a core organizing member of the CSE Media and Website team for Dastaan 2025.", "Dastaan '25 Core Organizing Committee recognition", "certificate"),
    ],
  },
  {
    id: "college-competition-wins",
    dateLabel: "2025",
    sortDate: "2025-04-01",
    era: "btech",
    themes: ["compete"],
    title: "Two Events, Two Second Places",
    summary: "Placed second in both Ctrl Alt Compete and Code Survival at Amritakalanjali.",
    details: "Worked with peers through technical problem-solving and simulation-style programming challenges.",
    postUrl: linkedInPost("7332655830753779713"),
    media: [
      media(17, 1, 800, 564, "Certificate for second place in Ctrl Alt Compete.", "Ctrl Alt Compete certificate", "certificate"),
      media(17, 2, 800, 534, "Certificate for second place in Code Survival.", "Code Survival certificate", "certificate"),
      media(17, 4, 800, 450, "Students participating in the Code Survival event.", "Code Survival event"),
    ],
  },
  {
    id: "first-research-paper",
    dateLabel: "2025",
    sortDate: "2025-01-15",
    era: "btech",
    themes: ["learn", "build"],
    title: "First Research Paper Presentation",
    summary: "Presented research on a voice-activated framework for automated penetration testing.",
    details: "The work explored hands-free threat detection using voice commands and multi-agent security automation.",
    postUrl: linkedInPost("7292936405125591040"),
    media: [media(25, 1, 800, 1131, "CRM2025 certificate recognizing Nishith's research-paper presentation.", "CRM2025 presentation certificate", "certificate")],
  },
  {
    id: "ux-workshop-challenge",
    dateLabel: "January 30, 2025",
    sortDate: "2025-01-30",
    era: "btech",
    themes: ["learn", "compete", "build"],
    title: "Second Place in the UX Challenge",
    summary: "Redesigned Amrita's homepage during a hands-on workshop led by Google Lead Designer Trivikram Annamalai.",
    details: "The team prototyped a persona-aware, decluttered university experience with an AI-assisted route to documents, links, events, achievements, and academic information—all within the one-hour challenge.",
    postUrl: linkedInPost("7305261501416648704"),
    fieldNotes: [
      { label: "Participant reflection", url: linkedInPost("7305261501416648704") },
      { label: "University event recap", url: linkedInPost("7296156349044854784") },
    ],
    media: [
      media(21, 1, 800, 578, "Certificate recognizing Nishith's second place in the GDGoC ASEB UX Workshop and Challenge.", "UX Workshop & Challenge second-place certificate", "certificate"),
      media(21, 2, 800, 600, "Students and facilitators gathered after the GDGoC ASEB UX Workshop and Challenge.", "UX workshop participants"),
      media(21, 3, 800, 450, "A team member presents the redesigned Amrita homepage during the UX challenge.", "Presenting the persona-aware homepage concept"),
      media(21, 4, 800, 450, "Nishith presents the team's Amrita homepage prototype during the UX challenge.", "Demonstrating the one-hour UX prototype"),
    ],
  },
  {
    id: "microsoft-club-leadership",
    dateLabel: "2024–2025",
    sortDate: "2024-12-01",
    era: "btech",
    themes: ["lead", "learn"],
    title: "Building a Student Tech Community",
    summary: "Co-founded and served as Vice President of Microsoft Ignite Students Club ASEB.",
    details: "Led technical upskilling, community events, and club-building work while progressing as a Microsoft Learn Student Ambassador.",
    postUrl: linkedInPost("7332652966677487616"),
    fieldNotes: [
      { label: "Club leadership reflection", url: linkedInPost("7332652966677487616") },
      { label: "MLSA Beta milestone", url: linkedInPost("7220762297537900544") },
      { label: "Joining the MLSA cohort", url: linkedInPost("7186551761434734592") },
    ],
    media: [
      media(18, 3, 800, 1422, "Trophy recognizing Nishith as Vice President of Microsoft Ignite Students Club ASEB.", "Microsoft student club leadership trophy"),
      media(18, 4, 800, 600, "Student club members and mentor celebrating with trophies and certificates.", "Microsoft Ignite Students Club ASEB team"),
    ],
  },
  {
    id: "project-x-recognition",
    dateLabel: "2024",
    sortDate: "2024-11-01",
    era: "btech",
    themes: ["build", "compete"],
    title: "Project X Earns Global Recognition",
    summary: "Received an honorable mention in the Microsoft Developers AI Learning Hackathon.",
    details: "Project X grew from a database course project into a generative-AI learning platform recognized from more than 9,500 participants.",
    postUrl: linkedInPost("7247531294039908353"),
    media: [media(31, 1, 800, 800, "Graphic for the Microsoft Developers AI Learning Hackathon.", "Project X honorable mention")],
  },
  {
    id: "misc-inauguration",
    dateLabel: "2024",
    sortDate: "2024-03-01",
    era: "btech",
    themes: ["lead", "build", "learn"],
    title: "Launching Microsoft Ignite Students Club ASEB",
    summary: "Co-founded MISC and helped turn a shared vision for peer-led technology learning into a campus community.",
    details: "As Vice President, introduced the club's founding team, identity, Digital Badges platform, and Azure Blueprint Architect at its inauguration, which also featured an opening Ignite Talk on generative AI by Mahesh Arali.",
    postUrl: linkedInPost("7174771974785626112"),
    fieldNotes: [
      { label: "Inauguration reflection", url: linkedInPost("7174771974785626112") },
      { label: "Club website", url: "https://ignitestudents.club" },
    ],
    media: [
      media(45, 2, 2048, 1365, "Nishith receives a commemorative club badge during the MISC inauguration ceremony.", "A founding moment at the MISC inauguration"),
      media(45, 3, 2048, 1365, "Nishith speaks from the auditorium lectern during the launch of Microsoft Ignite Students Club ASEB.", "Introducing the club at its inauguration"),
      media(45, 4, 2048, 1365, "Nishith presents the club's plans and projects during the MISC inauguration.", "Presenting the MISC roadmap"),
      media(45, 5, 2048, 1365, "Nishith demonstrates the Digital Badges platform during the MISC inauguration ceremony.", "Demonstrating the Digital Badges platform"),
    ],
  },
  {
    id: "microsoft-security-research",
    dateLabel: "September–November 2024",
    sortDate: "2024-11-30",
    era: "btech",
    themes: ["learn", "compete"],
    title: "Two Microsoft Security Bounties",
    summary: "Earned two MSRC acknowledgements and bug bounties for responsible Microsoft Forms research.",
    details: "The follow-up report identified a missed fix from the earlier Forms XSS finding, demonstrating persistence through coordinated vulnerability disclosure without publishing sensitive report details.",
    postUrl: linkedInPost("7278890683178868736"),
    fieldNotes: [
      { label: "First bounty", url: linkedInPost("7255866668323647490") },
      { label: "Follow-up bounty", url: linkedInPost("7278890683178868736") },
    ],
    media: [
      media(28, 1, 738, 1536, "Email from Microsoft Security Response Center confirming the first bounty award.", "First Microsoft security bounty confirmation"),
      media(26, 1, 738, 1536, "Email from Microsoft Security Response Center confirming eligibility for a second bounty.", "Second Microsoft security bounty confirmation"),
      media(26, 2, 800, 400, "Microsoft Security Response Center acknowledgements listing Nishith twice in 2024.", "Two MSRC acknowledgements in 2024"),
    ],
  },
  {
    id: "codechef-vice-president",
    dateLabel: "2023–2024",
    sortDate: "2024-06-01",
    era: "btech",
    themes: ["lead", "learn"],
    title: "Vice President, CodeChef ASEB",
    summary: "Led workshops, introductory sessions, and student programming activities.",
    details: "The role connected competitive programming, peer learning, event operations, and cross-year community building.",
    postUrl: linkedInPost("7234578355478507522"),
    media: [
      media(34, 1, 800, 541, "Certificate of appreciation for serving as a CodeChef ASEB office bearer.", "CodeChef ASEB office-bearer certificate", "certificate"),
      media(56, 1, 720, 720, "CodeChef ASEB students and faculty gathered for a chapter event.", "CodeChef ASEB community"),
    ],
  },
  {
    id: "kalanjali-2024",
    dateLabel: "April 2024",
    sortDate: "2024-04-20",
    era: "btech",
    themes: ["build", "lead", "learn"],
    title: "Shipping Kalanjali 2024",
    summary: "Built and deployed the cultural-fest website, then co-organized AI Artistry & PrisonCTF.",
    details: "Used React, Docker, GitHub Actions, Docker Hub, and college infrastructure for the website; the first MLSA event added an LLM-security CTF built with Ollama, Gemma 2B, Copilot Studio, and Cloud Run.",
    postUrl: linkedInPost("7200878397386874880"),
    fieldNotes: [
      { label: "Festival website", url: linkedInPost("7200878397386874880") },
      { label: "AI Artistry & PrisonCTF", url: linkedInPost("7201241429791105025") },
    ],
    media: [
      media(40, 2, 640, 360, "Kalanjali 2024 website visual featuring hands creating traditional artwork.", "Kalanjali 2024 website and Rituals theme"),
      media(39, 1, 800, 600, "Students and organizers gathered after the AI Artistry and PrisonCTF event.", "AI Artistry & PrisonCTF participants"),
      media(39, 3, 800, 360, "A speaker addressing students during AI Artistry and PrisonCTF.", "Running the first MLSA ambassador event"),
      media(39, 4, 800, 1065, "Dashboard showing solve and submission statistics for the PrisonCTF challenges.", "PrisonCTF challenge statistics"),
    ],
  },
  {
    id: "project-x-bootcamp",
    dateLabel: "2023",
    sortDate: "2023-12-01",
    era: "btech",
    themes: ["build", "learn"],
    title: "Project X at the GDSC Regional Bootcamp",
    summary: "Project X was shortlisted for the GDSC India Solution Challenge Regional Bootcamp.",
    details: "The experience added mentorship, product feedback, and a stronger path from course work to a user-facing AI platform.",
    postUrl: linkedInPost("7157074251731132416"),
    media: [
      media(47, 1, 800, 918, "Poster for the Solution Challenge India Regional Bootcamp.", "GDSC India Solution Challenge Regional Bootcamp"),
      media(47, 2, 800, 1422, "Students at the Solution Challenge Regional Bootcamp.", "Regional Bootcamp participants"),
    ],
  },
  {
    id: "hogwarts-hackfest",
    dateLabel: "November 26, 2023",
    sortDate: "2023-11-26",
    era: "btech",
    themes: ["compete", "build"],
    title: "Second Place at Hogwarts Hackfest",
    summary: "Built an AI-assisted dermatology prototype during Dastaan's Harry Potter-themed coding sprint.",
    details: "Led the frontend, backend, and Google PaLM integration for a chat experience that combined a skin-image classifier with symptom-aware guidance, delivering a working prototype in roughly five hours.",
    postUrl: linkedInPost("7200855254182055936"),
    fieldNotes: [
      { label: "Team reflection", url: linkedInPost("7200855254182055936") },
      { label: "Event recap", url: linkedInPost("7207103569039159296") },
    ],
    media: [
      media(41, 1, 800, 449, "Nishith receives the second-place award during Hogwarts Hackfest.", "Receiving the Hogwarts Hackfest award"),
      media(41, 2, 800, 581, "Certificate recognizing Nishith's second place at Hogwarts Hackfest.", "Hogwarts Hackfest second-place certificate", "certificate"),
      media(41, 3, 800, 600, "Hogwarts Hackfest participants celebrate with certificates and awards.", "Hogwarts Hackfest closing celebration"),
      media(41, 4, 800, 600, "Students and faculty gather on the Amrita staircase with Hogwarts Hackfest certificates.", "Hogwarts Hackfest participants and faculty"),
    ],
  },
  {
    id: "college-bus-tracker",
    dateLabel: "May 2023",
    sortDate: "2023-05-30",
    era: "btech",
    themes: ["build", "compete"],
    title: "First College Product Pitch",
    summary: "Pitched a custom college bus tracker and secured second place in The Next Big Thing.",
    details: "The project combined realtime location tracking with a practical problem experienced by the campus community.",
    postUrl: linkedInPost("7117576609070518272"),
    media: [
      media(54, 1, 800, 533, "Presenting a GPS module during the college bus tracker pitch.", "College Bus Tracker prototype"),
      media(54, 4, 800, 533, "Nishith speaking at a podium during a college startup pitching event.", "The Next Big Thing pitch"),
      media(32, 1, 800, 577, "Certificate for second place in the software category at Innovation Day.", "Innovation Day second-place certificate", "certificate"),
    ],
  },
  {
    id: "ssf-completion",
    dateLabel: "October 2022",
    sortDate: "2022-10-01",
    era: "origins",
    themes: ["build", "learn"],
    title: "From SSF to Amrita",
    summary: "Completed the Swachhta Saarthi Fellowship, then began B.Tech CSE at Amrita Bengaluru.",
    details: "Plastic Analyser received additional fellowship recognition through the WoW programme before the next chapter began across software, research, security, cloud, competitions, and student leadership.",
    postUrl: null,
    media: [certificate("SSF_Completion_Certificate.webp", 1200, 850, "Certificate marking completion of the Swachhta Saarthi Fellowship.", "SSF completion certificate")],
  },
  {
    id: "school-leadership",
    dateLabel: "2021–2022",
    sortDate: "2021-09-01",
    era: "origins",
    themes: ["lead"],
    title: "IT Captain and School Leadership",
    summary: "Served as IT Captain while taking on wider school leadership responsibilities.",
    details: "Combined school office-bearer responsibility with technical interests, academic work, and student-community leadership.",
    postUrl: linkedInPost("7119046599636393984"),
    media: [media(53, 3, 748, 1156, "School prize-day collage featuring ISC science-stream achievers.", "Bishop Cotton Boys' School prize day")],
  },
  {
    id: "ssf-fellowship",
    dateLabel: "May 2021",
    sortDate: "2021-05-01",
    era: "origins",
    themes: ["build", "compete"],
    title: "Plastic Analyser and the SSF Fellowship",
    summary: "Plastic Analyser was selected for the Swachhta Saarthi Fellowship under the Waste to Wealth Mission.",
    details: "The fellowship connected an early machine-learning project with a national programme supported by the Office of the Principal Scientific Adviser to the Government of India.",
    postUrl: null,
    media: [certificate("SSF_Selection_Certificate.webp", 1200, 850, "Certificate confirming selection for the Swachhta Saarthi Fellowship.", "SSF selection certificate")],
  },
  {
    id: "synchronize-2021",
    dateLabel: "August 26–27, 2021",
    sortDate: "2021-08-27",
    era: "origins",
    themes: ["lead"],
    title: "Head of Organizing Committee, Synchronize 2021",
    summary: "Led the organizing committee and served as Event Head for Graphene at the school's Science and IT Fest.",
    details: "Coordinated organizing work across the two-day Synchronize 2021 festival while also leading the Graphene event.",
    postUrl: null,
    media: [
      certificate("Nishith-P-OC_page-0001.webp", 1650, 1275, "Bishop Cotton Boys' School certificate recognizing Nishith as Head of the Organizing Committee for Synchronize 2021.", "Synchronize 2021 Head of Organizing Committee certificate"),
      certificate("Nishith-P-Event-Heads_page-0001.webp", 1650, 1275, "Bishop Cotton Boys' School certificate recognizing Nishith as Event Head for Graphene at Synchronize 2021.", "Synchronize 2021 Graphene Event Head certificate"),
    ],
  },
  {
    id: "google-code-programs",
    dateLabel: "2017–2019",
    sortDate: "2019-12-01",
    era: "origins",
    themes: ["build", "compete", "learn"],
    title: "Learning in the Open",
    summary: "Progressed from Google Code-in participant to 2019 finalist and Google Code to Learn winner.",
    details: "Completed 34 open-source tasks as a FOSSASIA finalist in Google Code-in 2019, then built Plastic Analyser as a winning Grade 10 machine-learning project.",
    postUrl: null,
    media: [
      certificate("GCI-2019-Certificate-4855824917200896_page-0001.webp", 1200, 850, "Google Code-in 2019 certificate.", "Google Code-in 2019 finalist certificate"),
      certificate("Google-C2L-Certificate_page-0001.webp", 1200, 850, "Google Code to Learn certificate for Plastic Analyser.", "Google Code to Learn 2019 winner certificate"),
      certificate("Award_letter227_page-0001.webp", 1275, 1650, "Google award letter confirming Nishith as a FOSSASIA finalist in Google Code-in 2019 after completing 34 tasks.", "Google Code-in 2019 finalist award letter"),
    ],
  },
]

export const credentials = [
  { id: "openenv", title: "OpenEnv Hackathon Round 1 Qualified", issuer: "Meta, PyTorch, OpenEnv & Scaler", date: "April 2026", result: "Grand Finale qualifier", image: journeyEntries.find((entry) => entry.id === "openenv-finalist").media[0], relatedJourneyId: "openenv-finalist" },
  { id: "ux-challenge", title: "Hands-on UX Workshop & Challenge", issuer: "GDGoC ASEB", date: "January 2025", result: "Second place", image: journeyEntries.find((entry) => entry.id === "ux-workshop-challenge").media[0], relatedJourneyId: "ux-workshop-challenge" },
  { id: "dastaan", title: "Hack Your Life", issuer: "Dastaan '25", date: "October 2025", result: "Second place", image: journeyEntries.find((entry) => entry.id === "dastaan-2025").media[0], relatedJourneyId: "dastaan-2025" },
  { id: "ctrl-alt", title: "Ctrl Alt Compete", issuer: "Computer Society of India", date: "2025", result: "Second place", image: journeyEntries.find((entry) => entry.id === "college-competition-wins").media[0], relatedJourneyId: "college-competition-wins" },
  { id: "code-survival", title: "Code Survival", issuer: "Amritakalanjali", date: "2025", result: "Second place", image: journeyEntries.find((entry) => entry.id === "college-competition-wins").media[1], relatedJourneyId: "college-competition-wins" },
  { id: "crm-2025", title: "Research Paper Presentation", issuer: "CRM 2025", date: "2025", result: "Presenter", image: journeyEntries.find((entry) => entry.id === "first-research-paper").media[0], relatedJourneyId: "first-research-paper" },
  { id: "microsoft-club", title: "Microsoft Ignite Students Club ASEB", issuer: "Amrita Vishwa Vidyapeetham", date: "2024–2025", result: "Office Bearer", image: media(18, 2, 800, 570, "Certificate recognizing Nishith as a Microsoft Ignite Students Club ASEB office bearer.", "Microsoft student club office-bearer certificate", "certificate"), relatedJourneyId: "microsoft-club-leadership" },
  { id: "mlsa-beta", title: "Microsoft Learn Student Ambassador", issuer: "Microsoft", date: "2024", result: "Advanced to Beta", image: media(37, 1, 800, 927, "Microsoft Learn Student Ambassador Beta certificate displayed with Microsoft welcome items.", "Microsoft Learn Student Ambassador Beta recognition", "certificate"), relatedJourneyId: "microsoft-club-leadership" },
  { id: "mlsa-alpha", title: "Microsoft Learn Student Ambassador", issuer: "Microsoft", date: "2024", result: "Alpha cohort", image: media(42, 2, 800, 618, "Certificate recognizing Nishith as a Microsoft Learn Student Ambassador in the 2024 Alpha cohort.", "Microsoft Learn Student Ambassador Alpha certificate", "certificate"), relatedJourneyId: "microsoft-club-leadership" },
  { id: "aws-cloud-foundations", title: "AWS Academy Cloud Foundations", issuer: "AWS Academy", date: "During B.Tech", result: "Graduate", image: certificate("AWS_Academy_Cloud_Foundations.webp", 1200, 850, "AWS Academy Cloud Foundations graduate certificate.", "AWS Academy Cloud Foundations certificate"), relatedJourneyId: null },
  { id: "codechef", title: "CodeChef ASEB Student Chapter", issuer: "Amrita Vishwa Vidyapeetham", date: "2023–2024", result: "Vice President", image: journeyEntries.find((entry) => entry.id === "codechef-vice-president").media[0], relatedJourneyId: "codechef-vice-president" },
  { id: "innovation-day", title: "Innovation Day", issuer: "Institution's Innovation Council", date: "2023", result: "Second place — Software", image: media(32, 1, 800, 577, "Certificate for second place in the software category at Innovation Day.", "Innovation Day certificate", "certificate"), relatedJourneyId: "college-bus-tracker" },
  { id: "ssf-completion", title: "Swachhta Saarthi Fellowship", issuer: "Office of the Principal Scientific Adviser to the Government of India", date: "October 2022", result: "Completed", image: journeyEntries.find((entry) => entry.id === "ssf-completion").media[0], relatedJourneyId: "ssf-completion" },
  { id: "synchronize-2021", title: "Synchronize 2021", issuer: "Bishop Cotton Boys' School", date: "August 2021", result: "Head of Organizing Committee", image: journeyEntries.find((entry) => entry.id === "synchronize-2021").media[0], relatedJourneyId: "synchronize-2021" },
  { id: "gci-2019", title: "Google Code-in 2019", issuer: "Google / FOSSASIA", date: "2019", result: "Finalist · 34 tasks completed", image: journeyEntries.find((entry) => entry.id === "google-code-programs").media[2], relatedJourneyId: "google-code-programs" },
  { id: "code-to-learn", title: "Google Code to Learn", issuer: "Google", date: "2019", result: "Winner — Grade 10 Machine Learning", image: journeyEntries.find((entry) => entry.id === "google-code-programs").media[1], relatedJourneyId: "google-code-programs" },
]

export const galleryAlbums = journeyEntries
  .filter((entry) => entry.media.length > 0 && entry.era === "btech")
  .map((entry) => ({ id: entry.id, title: entry.title, date: entry.dateLabel, themes: entry.themes, postUrl: entry.postUrl, fieldNotes: entry.fieldNotes, media: entry.media }))

export const journeyThemes = ["all", "build", "compete", "lead", "learn"]
